### ISSUE TITLE
Consider using explicit form binding in minimal APIs

### ISSUE THREAD

**Issue by captainsafia** [TDMR87/Pomoda#1]
@TDMR87 Great sample here! I love the way you've structured this project.

I noticed that the API endpoints for querying on movies read parameters from the form body but did not leverage the form binding support in minimal APIs that was released in .NET 8.

You can read more about this feature at https://learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis/parameter-binding. 

Thoughts on this?

**Comment by TDMR87** [comment]
@captainsafia Good catch! This is definitely a no-brainer and I have now implemented this in the commit [612fe5f](https://github.com/TDMR87/Pomoda/commit/612fe5fbcb59ec0af7bd264885e21c62eda98beb).

Note: to make this work with the form binding attributes I had to explicitly disable AntiforgeryTokenValidation for that endpoint since minimal APIs seem to require it by default when accepting form data. But disabling it shouldn't be a huge deal in this case.

Thank you for taking a look at the repo and for this improvement suggestion btw. 👍

**Comment by captainsafia** [comment]
> Note: to make this work with the form binding attributes I had to explicitly disable AntiforgeryTokenValidation for that endpoint since minimal APIs seem to require it by default when accepting form data. But disabling it shouldn't be a huge deal in this case.

Yeah, we just documented this behavior breaking change over at https://github.com/aspnet/Announcements/issues/509. Using `DisableAntiforgery` is sufficient here.

Thanks for making this update!
